//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSTSMonitor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class VSTSMonitor : global::System.Configuration.ApplicationSettingsBase {
        
        private static VSTSMonitor defaultInstance = ((VSTSMonitor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VSTSMonitor())));
        
        public static VSTSMonitor Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1601-01-01")]
        public global::System.DateTime LastChecked {
            get {
                return ((global::System.DateTime)(this["LastChecked"]));
            }
            set {
                this["LastChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowPopup {
            get {
                return ((bool)(this["ShowPopup"]));
            }
            set {
                this["ShowPopup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextToSpeech {
            get {
                return ((bool)(this["TextToSpeech"]));
            }
            set {
                this["TextToSpeech"] = value;
            }
        }
    }
}
